import { Annotation, MessagesAnnotation } from "@langchain/langgraph";

/**
 * ValidatorStateAnnotation defines every channel in the graph's shared state.
 *
 * Channel semantics:
 *  - string channels (initialIdea, roastReport): default reducer = replace on update
 *  - array channels (interrogationQuestions, userAnswers): explicit replace reducer so
 *    nodes always overwrite rather than append (we want a single, authoritative list)
 *  - messages: inherited from MessagesAnnotation — appends and deduplicates by ID
 */
export const ValidatorStateAnnotation = Annotation.Root({
  // Spread the standard messages channel (add/dedup by message ID)
  ...MessagesAnnotation.spec,

  // The raw startup idea submitted by the user
  initialIdea: Annotation<string>(),

  // 3 questions generated by the interrogator node
  interrogationQuestions: Annotation<string[]>({
    reducer: (_, incoming) => incoming ?? [],
    default: () => [],
  }),

  // Answers collected from the user at the interrupt boundary
  userAnswers: Annotation<string[]>({
    reducer: (_, incoming) => incoming ?? [],
    default: () => [],
  }),

  // Final roast report produced by the roaster node
  roastReport: Annotation<string>(),
});

export type ValidatorState = typeof ValidatorStateAnnotation.State;
