import { Annotation, MessagesAnnotation } from "@langchain/langgraph";

/**
 * ValidatorStateAnnotation defines every channel in the graph's shared state.
 *
 * Channel semantics:
 *  - string channels (initialIdea, roastReport, researchSummary): default reducer = replace
 *  - number channels (viabilityScore): replace on update
 *  - array channels (interrogationQuestions, userAnswers): explicit replace reducer
 *  - messages: inherited from MessagesAnnotation — appends and deduplicates by ID
 */
export const ValidatorStateAnnotation = Annotation.Root({
  // Spread the standard messages channel (add/dedup by message ID)
  ...MessagesAnnotation.spec,

  // The raw startup idea submitted by the user
  initialIdea: Annotation<string>(),

  // Market research summary produced by the research node (empty if Tavily not configured)
  researchSummary: Annotation<string>({
    reducer: (_, incoming) => incoming ?? "",
    default: () => "",
  }),

  // N questions generated by the interrogator node (N = INTERROGATION_QUESTIONS env var, default 3)
  interrogationQuestions: Annotation<string[]>({
    reducer: (_, incoming) => incoming ?? [],
    default: () => [],
  }),

  // Answers collected from the user at the interrupt boundary
  userAnswers: Annotation<string[]>({
    reducer: (_, incoming) => incoming ?? [],
    default: () => [],
  }),

  // Final roast report produced by the roaster node (markdown)
  roastReport: Annotation<string>(),

  // Viability score 0-100 extracted from the roast report
  viabilityScore: Annotation<number>({
    reducer: (_, incoming) => incoming ?? 0,
    default: () => 0,
  }),
});

export type ValidatorState = typeof ValidatorStateAnnotation.State;
